## 1.	Write a Python Program to find sum of array?

In [2]:
import numpy as np

In [14]:
a = np.array([[1,2,3,4,5],[11,22,33,44,55]])
print(a)
print('Sum of array is: ',np.sum(a))

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
Sum of array is:  180


## 2.	Write a Python Program to find largest element in an array?

In [17]:
a = np.array([[1,2,3,4,5],[11,22,19,55,55]])
print(a)

[[ 1  2  3  4  5]
 [11 22 19 55 55]]


In [19]:
print(f'Max element in the above array is {np.max(a)}')

Max element in the above array is 55


## 3.	Write a Python Program for array rotation?

##### In the left rotation, each element of the array will be shifted to its left by one position and the first element of the array will be added to end of the list. This process will be followed for a specified number of times.

In [56]:
def array_rotation(arr,n,rotation):
    if rotation  == 'left':
        for i in range(0,n):
            first = arr[0]
        
            for j in range(0,len(arr)-1):
                arr[j] = arr[j+1]
            arr[len(arr)-1] = first
        return arr
    else:
        for i in range(0,n-1):
            #print(i)
            first = arr[0]
        
            for j in range(0,len(arr)-1):
                #print(arr[j],arr[j+1])
                arr[j] = arr[j+1]
            arr[len(arr)-1] = first
            #print("Arr: ",arr)
        return arr

In [57]:
a = np.array([1,2,3,4,5])

## print original array
print("Original Array: ")
for i in range(0,len(a)):
    print(a[i],end=" ")


Original Array: 
1 2 3 4 5 

In [37]:
array_rotation(a,3,'left')

array([4, 5, 1, 2, 3])

In [58]:
array_rotation(a,3,'right')

array([3, 4, 5, 1, 2])

## 4.	Write a Python Program to Split the array and add the first part to the end?

In [81]:
def split_array(arr,element):
    if element in a:
        n = np.where(arr == element)[0][0]
        for i in range(0,n):
            first = arr[0]

            for j in range(0,len(arr)-1):
                arr[j] = arr[j+1]
            arr[len(arr)-1] = first
        return arr
    else:
        return "Element Not in Array!!"

In [82]:
a = np.array([1,2,3,4,5,11,22,34,55,67,87])

## print original array
print("Original Array: ")
for i in range(0,len(a)):
    print(a[i],end=" ")

Original Array: 
1 2 3 4 5 11 22 34 55 67 87 

In [83]:
split_array(a,99)

'Element Not in Array!!'

In [84]:
split_array(a,34)

array([34, 55, 67, 87,  1,  2,  3,  4,  5, 11, 22])

## 5.	Write a Python Program to check if given array is Monotonic?

##### An array is said to be monotonic in nature if it is either continuously increasing or continuously decreasing

In [130]:
def monotonic_arr(arr):
    if all(arr[i] <= arr[i + 1] for i in range(len(arr) - 1)): return "Array is Monotonous, Trend is increasing" 
    elif all(arr[i] >= arr[i + 1] for i in range(len(arr) - 1)):
        return "Array is Monotonous, Trend is Decreasing"
    return "Not Monotonic array"

In [131]:
a = np.array([1,2,3,4,5,11,22,34,55,67,87])

## print original array
print("Original Array A: ")
for i in range(0,len(a)):
    print(a[i],end=" ")

Original Array A: 
1 2 3 4 5 11 22 34 55 67 87 

In [132]:
b = np.array([11,22,3,4,5,11,22,34,55,67,87])

## print original array
print("Original Array B: ")
for i in range(0,len(b)):
    print(b[i],end=" ")

Original Array B: 
11 22 3 4 5 11 22 34 55 67 87 

In [135]:
c = np.array([11,9,8,7,6])

## print original array
print("Original Array C: ")
for i in range(0,len(c)):
    print(c[i],end=" ")

Original Array C: 
11 9 8 7 6 

In [133]:
monotonic_arr(a)

'Array is Monotonous, Trend is increasing'

In [134]:
monotonic_arr(b)

'Not Monotonic array'

In [136]:
monotonic_arr(c)

'Array is Monotonous, Trend is Decreasing'